[package]
name = "strata-ir"
version = "0.1.0"
edition = "2024"

[lib]
name = "strata_ir"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
blake3 = { workspace = true }
smol_str = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
